CREATE TABLE workspace (id TEXT PRIMARY KEY, doc TEXT NOT NULL, rev INTEGER NOT NULL DEFAULT 1);
CREATE TABLE sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE login_limits (id TEXT PRIMARY KEY, attempts INTEGER NOT NULL DEFAULT 0, expires INTEGER NOT NULL);
