import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../dist/server/index.js';
import {aiPrompt,parseAIResponse,generateAI} from '../worker/ai.mjs';
const result={kind:'draft',title:'검증된 제목',disclosure:'',body:'확인한 정보로 작성했어요.',questions:[],warnings:[],linkPositions:[],summary:'구성에 맞춘 초안'};
const response=(r=result)=>({status:'completed',output:[{type:'web_search_call',status:'completed'},{type:'message',content:[{type:'output_text',text:JSON.stringify(r),annotations:[{type:'url_citation',url:'https://official.example/event',title:'행사 공식 안내'}]}]}],usage:{input_tokens:50,output_tokens:30}});
async function setup(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../drizzle/0000_workspace.sql',import.meta.url),'utf8'));const env={ADMIN_PASSWORD:'test-only',OPENAI_API_KEY:'test-provider-key',DB:{prepare(q){let args=[];return {bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}}}};let cookie='';const request=async(path,data)=>{const r=await worker.fetch(new Request('https://test.local'+path,{method:data?'POST':'GET',headers:{'oai-authenticated-user-id':'owner','Cookie':cookie,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})}),env);return {http:r.status,...await r.json()}};const login=await worker.fetch(new Request('https://test.local/api/login',{method:'POST',headers:{'oai-authenticated-user-id':'owner'},body:JSON.stringify({password:'test-only'})}),env);cookie=login.headers.get('set-cookie').split(';')[0];const item=(await request('/api/action',{action:'saveItem',item:{title:'검증 주제',type:'issue',draft:'내가 쓴 원고',notes:'이 표현을 살려주세요.'}})).result;return {request,item,env};}
async function provider(fn,run){const previous=globalThis.fetch;globalThis.fetch=fn;try{return await run();}finally{globalThis.fetch=previous;}}
const generation=item=>({itemId:item.id,mode:'draft',requestId:crypto.randomUUID(),verifyLatest:true});
test('인증이 없거나 AI 키가 없으면 생성하지 않는다',async()=>{const {request,item,env}=await setup();delete env.OPENAI_API_KEY;assert.equal((await request('/api/ai/write',generation(item))).http,503);assert.equal((await request('/api/state')).state.tasks.length,0);assert.equal((await worker.fetch(new Request('https://test.local/api/ai/write',{method:'POST',body:'{}'}),env)).status,401);});
test('생성 결과와 출처를 분리하고 적용 전 원고를 보존하며 되돌릴 수 있다',async()=>{const {request,item}=await setup();let calls=0;await provider(async(url,opts)=>{calls++;assert.equal(url,'https://api.openai.com/v1/responses');const p=JSON.parse(opts.body);assert.equal(p.store,false);assert.equal(p.tools[0].type,'web_search');assert.equal(p.tool_choice,'required');assert.match(p.instructions,/기억나지/);return Response.json(response());},async()=>{const input=generation(item),first=await request('/api/ai/write',input);assert.equal(first.http,200);assert.equal(first.task.status,'완료');assert.equal(first.task.result.sources.length,1);assert.equal((await request('/api/state')).state.items[0].draft,item.draft);await request('/api/ai/write',input);assert.equal(calls,1);const applied=await request('/api/ai/apply',{taskId:first.task.id});assert.equal(applied.result.status,'초안 작성');assert.equal(applied.result.draft,'검증된 제목\n\n확인한 정보로 작성했어요.');assert.doesNotMatch(applied.result.draft,/official.example/);assert.equal((await request('/api/ai/apply',{taskId:first.task.id})).http,400);assert.equal((await request('/api/ai/undo',{taskId:first.task.id})).result.draft,item.draft);});});
test('요청 후 원고를 고쳤다면 AI 적용을 거절한다',async()=>{const {request,item}=await setup();await provider(async()=>Response.json(response()),async()=>{const done=await request('/api/ai/write',generation(item));await request('/api/action',{action:'saveItem',item:{id:item.id,title:item.title,draft:'새로 수정한 내 원고'}});assert.equal((await request('/api/ai/apply',{taskId:done.task.id})).http,409);assert.equal((await request('/api/state')).state.items[0].draft,'새로 수정한 내 원고');});});
test('선택 영역은 주변 원고를 보존하며 제목 요청은 전체 원고에 적용하지 않는다',async()=>{const {request,item}=await setup();await provider(async()=>Response.json(response({...result,kind:'partial',body:'새 부분'})),async()=>{const done=await request('/api/ai/write',{...generation(item),mode:'revision',scope:'selection',instruction:'선택한 부분만 수정',range:{start:3,end:4}});assert.equal(done.http,200);const applied=await request('/api/ai/apply',{taskId:done.task.id});assert.equal(applied.result.draft,item.draft.slice(0,3)+'새 부분'+item.draft.slice(4));});await provider(async()=>Response.json(response({...result,kind:'titles',body:'제목 1\n제목 2\n제목 3'})),async()=>{const done=await request('/api/ai/write',{...generation(item),mode:'revision',scope:'titles',instruction:'제목 3개'});assert.equal(done.http,200);assert.equal((await request('/api/ai/apply',{taskId:done.task.id})).http,400);});});
test('필수 질문을 세 개 이하로 분리하고 질문 결과를 원고에 적용하지 않는다',async()=>{const {request,item}=await setup();await provider(async()=>Response.json(response({...result,kind:'questions',body:'',questions:['제공받은 항목이 무엇인가요?']})),async()=>{const done=await request('/api/ai/write',generation(item));assert.equal(done.task.status,'확인 필요');assert.equal((await request('/api/ai/apply',{taskId:done.task.id})).http,400);assert.equal((await request('/api/state')).state.items[0].draft,item.draft);});});
test('외부 서비스 오류와 잘못된 결과는 실패로 기록하고 비밀·원고를 노출하거나 덮어쓰지 않는다',async()=>{const {request,item}=await setup();await provider(async()=>new Response('secret-provider-detail',{status:401}),async()=>{const done=await request('/api/ai/write',generation(item));assert.equal(done.http,502);assert.equal(done.task.status,'실패');assert.doesNotMatch(JSON.stringify(done),/test-provider-key|secret-provider-detail/);assert.equal((await request('/api/state')).state.items[0].draft,item.draft);});await provider(async()=>Response.json(response({...result,body:''})),async()=>{assert.equal((await request('/api/ai/write',generation(item))).task.status,'실패');});});
test('진행 중인 같은 글의 중복 요청과 일일 한도를 제한한다',async()=>{const {request,item,env}=await setup();let release;const gate=new Promise(r=>release=r);await provider(async()=>{await gate;return Response.json(response());},async()=>{const first=request('/api/ai/write',generation(item));for(let n=0;n<30;n++){if((await request('/api/state')).state.tasks.length)break;await new Promise(r=>setTimeout(r,2));}assert.equal((await request('/api/ai/write',generation(item))).http,409);release();await first;});env.AI_DAILY_LIMIT='1';assert.equal((await request('/api/ai/write',generation(item))).http,429);});
test('사진·PDF를 실제 입력하고 읽지 못한 첨부를 건너뛰지 않는다',async()=>{const env={OPENAI_API_KEY:'test-key',BUCKET:{async get(){return {async arrayBuffer(){return new Uint8Array([65,66]).buffer}}}}},state={settings:{editorRules:''},items:[],lessons:[],files:[{id:'pdf',key:'pdf',name:'조건.pdf',type:'application/pdf'},{id:'photo',key:'photo',name:'사진.jpg',type:'image/jpeg'}]},job={item:{title:'첨부 자료',attachmentIds:['pdf','photo']},mode:'draft',scope:'whole',verifyLatest:false};await generateAI(job,state,env,async(url,opts)=>{const p=JSON.parse(opts.body);assert.equal(p.input[0].content[1].type,'input_file');assert.match(p.input[0].content[1].file_data,/^data:application\/pdf;base64,/);assert.equal(p.input[0].content[3].type,'input_image');assert.equal(p.tools,undefined);return Response.json(response());});await assert.rejects(generateAI({...job,item:{...job.item,attachmentIds:['missing']}},state,env),/찾지 못했어요/);});
test('다른 글 경험은 말투 참고로만 쓰고 활성 학습 기준만 반영한다',()=>{const p=aiPrompt({item:{title:'이번 글'},mode:'draft'},{settings:{editorRules:'써즈 기준'},items:[{id:'old',status:'게시됨',title:'지난 여행',draft:'지난 표현'}],lessons:[{active:true,points:'사용',apply:'적용'},{active:false,points:'미검토 자료'}]});assert.match(p.instructions,/다른 글의 경험/);assert.match(p.input,/지난 표현/);assert.doesNotMatch(p.input,/미검토 자료/);});
test('미완료·거부·질문 초과 결과와 잘못된 인용 주소를 처리한다',()=>{assert.throws(()=>parseAIResponse({status:'incomplete'}),/끝나지/);assert.throws(()=>parseAIResponse({status:'completed',output:[{type:'message',content:[{type:'refusal'}]}]}),/처리하지/);assert.throws(()=>parseAIResponse(response({...result,kind:'questions',questions:['1','2','3','4']})),/질문 수/);const r=response({...result,body:'확인했어요. citeturn0search1'});r.output[1].content[0].annotations.push({type:'url_citation',url:'javascript:alert(1)'});assert.equal(parseAIResponse(r).sources.length,1);assert.equal(parseAIResponse(r).body,'확인했어요.');});
