import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {initialState} from '../worker/domain.mjs';
import {createAutomaticBrief,automaticContext,saveAutomaticDraft,automaticAssetPlan,attachAutomaticAsset,automaticPrepareInput} from '../worker/automatic.mjs';
const now='2026-10-06T04:00:00.000Z',hash=async text=>createHash('sha256').update(text).digest('hex');
const source={kind:'official',url:'https://www.japan.travel/',title:'공식 발표',checkedAt:now,facts:['공식 발표에서 확인한 변경 일정을 안내한다.']};
const brief=(extra={})=>({requestId:crypto.randomUUID(),title:'일본 여행 제도 변경 안내',lane:'asia-issue',scheduledAt:'2026-10-07T01:00',reason:'변경 전 준비할 여행 정보',region:'일본',sources:[source],...extra});
const content=input=>({...input,id:crypto.randomUUID(),createdAt:now,updatedAt:now,automatic:true,prep:{},attachmentIds:[]});
function fixture(){const s=initialState(),input=brief(),result=createAutomaticBrief(s,input,content,now);return {s,input,itemId:result.itemId};}
test('자동 기획은 실제 확인 자료를 요구하고 직접 원고·경험치·다른 종류 일정과 분리한다',()=>{const s=initialState();s.items.push({id:'manual',title:'직접 작성',draft:'사용자 원고',date:'2026-10-07',automatic:false});const old=structuredClone(s.items[0]),b=brief(),a=createAutomaticBrief(s,b,content,now);assert.equal(createAutomaticBrief(s,b,content,now).duplicate,true);assert.equal(s.items.length,2);assert.deepEqual(s.items[1],old);assert.equal(s.xp,0);assert.throws(()=>createAutomaticBrief(s,brief(),content,now),/이미/);assert.equal(s.items[0].status,'아이디어');assert.equal(a.itemId,s.items[0].id);});
test('공식 확인 시각·사실·01시와 상품의 실제 구매 링크를 검증한다',()=>{for(const sources of [[],[{...source,kind:'review'}],[{...source,checkedAt:'2026-10-04T04:00:00Z'}],[{...source,facts:[]}],[{...source,url:'http://example.com'}]])assert.throws(()=>createAutomaticBrief(initialState(),brief({sources}),content,now));assert.throws(()=>createAutomaticBrief(initialState(),brief({scheduledAt:'2026-10-07T02:00'}),content,now));assert.throws(()=>createAutomaticBrief(initialState(),brief({lane:'brand-shopping',product:{name:'상품',url:'https://smartstore.naver.com/shop/products/1',affiliateUrl:'https://brandconnect.naver.com/affiliate/products/1',disclosure:'판매 시 수수료를 제공받습니다.',ownerChannelConfirmed:true}}),content,now),/관리 화면/);});
test('자동 원고는 자료 변경·출처 누락·거짓 경험을 거절하고 실제 확인 원고만 반영한다',async()=>{const {s,itemId}=fixture(),ctx=await automaticContext(s,itemId,hash),body='확인한 공식 여행 정보를 안내하는 원고입니다. '.repeat(10),input={itemId,revision:ctx.revision,title:ctx.title,body,reviewed:true,latestInformationVerified:true,checkedSourceUrls:[source.url]};for(const bad of [{revision:'old'},{checkedSourceUrls:[]},{body:body+'제가 다녀왔는데요.'},{reviewed:false}])await assert.rejects(()=>saveAutomaticDraft(s,{...input,...bad},hash,now));await saveAutomaticDraft(s,input,hash,now);assert.equal(s.items[0].status,'초안 작성');assert.equal(s.items[0].draft,ctx.title+'\n\n'+body.trim());assert.equal(s.xp,0);assert.equal(s.publishJobs,undefined);await assert.rejects(()=>saveAutomaticDraft(s,input,hash,now),/변경/);});
test('자동 경로로 직접 원고·네이버 예약 원고·실행 중 원고를 덮어쓰지 않는다',async()=>{const {s,itemId}=fixture();s.items.push({id:'manual',draft:'직접 글',automatic:false});await assert.rejects(()=>saveAutomaticDraft(s,{itemId:'manual'},hash,now),/자동 글/);s.items[0].status='예약됨';await assert.rejects(()=>saveAutomaticDraft(s,{itemId},hash,now),/변경하지/);s.items[0].status='초안 작성';s.publishJobs=[{itemId,status:'확인 필요'}];await assert.rejects(()=>saveAutomaticDraft(s,{itemId},hash,now),/변경하지/);assert.equal(s.items[1].draft,'직접 글');});
test('사진 실제 파일 서명과 이용 근거를 검증하고 같은 파일은 중복 첨부하지 않는다',()=>{const {s,itemId}=fixture(),bytes=new Uint8Array([255,216,255,224,0]),input={itemId,name:'사진.jpg',rights:'licensed',sourceUrl:'https://commons.wikimedia.org/wiki/File:Photo.jpg',licenseUrl:'https://creativecommons.org/publicdomain/zero/1.0/',permissionText:'CC0',attribution:'촬영자 · CC0'};assert.throws(()=>automaticAssetPlan(s,input,new Uint8Array([60,115,118,103]),'a',now),/실제/);assert.throws(()=>automaticAssetPlan(s,{...input,licenseUrl:''},bytes,'a',now),/라이선스/);const plan=automaticAssetPlan(s,input,bytes,'hash',now);assert.equal(plan.file.type,'image/jpeg');attachAutomaticAsset(s,input,plan.file,now);assert.equal(automaticAssetPlan(s,input,bytes,'hash',now).duplicate,true);assert.equal(s.files.length,1);assert.equal(s.items[0].prep.photos,true);assert.equal(s.xp,0);});
test('발행 준비에 검수·사진 권한·정확한 자동 발행 종류와 시간을 넘긴다',()=>{const {s,itemId}=fixture();assert.throws(()=>automaticPrepareInput(s,{itemId}),/검수/);s.items[0].automaticResearch.draftReviewed=true;s.files.push({id:'photo',automaticRights:{rights:'licensed',licenseUrl:'https://creativecommons.org/publicdomain/zero/1.0/',caption:'도시 전경',attribution:'작가 · CC0'}});s.items[0].attachmentIds=['photo'];const p=automaticPrepareInput(s,{itemId,requestId:crypto.randomUUID(),lane:'manual',scheduledAt:'wrong'});assert.equal(p.lane,'asia-issue');assert.equal(p.scheduledAt,'2026-10-06T16:00:00.000Z');assert.equal(p.images[0].caption,'도시 전경 · 작가 · CC0');});
