import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {initialState} from '../worker/domain.mjs';
import {publicationTime,preparePublication,publicationChecks,publicationOverview,claimPublication,recordPublication,cancelPublication,recordPublishingAccess} from '../worker/publishing.mjs';
const hash=async s=>createHash('sha256').update(s).digest('hex');
const now='2026-10-06T00:00:00.000Z',runUrl='https://agent.tinyfish.ai/runs/7b9a3d97-e183-4b18-ab56-ed3f5ac05463';
function fixture(){const state=initialState();state.items.push({id:'item',title:'여행 정보',draft:'여행 정보\n\n확인한 여행 정보입니다.\n\n여행 준비 방법입니다.',channel:'blog',type:'info',status:'초안 작성',date:'',attachmentIds:['photo'],updatedAt:now});state.files.push({id:'photo',name:'직접 촬영.jpg',type:'image/jpeg',size:100,key:'files/photo'});recordPublishingAccess(state,{runUrl,blogId:'withsuzz',entryUrl:'https://blog.naver.com/PostWriteForm.naver?blogId=withsuzz',editorAccessible:true,loginRequired:false,accountMismatch:false,imageUploadVerified:true,imageVerification:'실제 이미지 삽입 확인 (테스트 fixture)',observedControls:['title','body','image','publish','reservation']},now);return state;}
function input(extra={}){return {itemId:'item',requestId:crypto.randomUUID(),title:'여행 정보',scheduledAt:'2026-10-06T09:00',lane:'manual',reviewed:true,images:[{fileId:'photo',afterParagraph:0,rights:'own'}],...extra};}
function proof(job,lease,extra={}){return {jobId:job.id,leaseId:lease.leaseId,outcome:'published',runUrl,verifiedTitle:job.title,bodyVerified:true,imagesVerified:true,verification:'실제 게시글의 제목·본문·사진을 재조회해 확인.',postUrl:'https://blog.naver.com/withsuzz/123456789',publishedAt:'2026-10-06T09:01:00+09:00',...extra};}
test('한국 시각을 정확하게 변환하고 존재하지 않는 날짜·시각을 거절한다',()=>{assert.equal(publicationTime('2026-10-07T01:00'),'2026-10-06T16:00:00.000Z');for(const x of ['2026-02-30T01:00','2026-10-06T24:00','2026-10-06T09:90','2026-10-06'])assert.throws(()=>publicationTime(x));});
test('발행 준비는 원고·일정·상태·경험치를 바꾸지 않고 요청 중복을 막는다',async()=>{const s=fixture(),before=structuredClone(s.items),data=input(),a=await preparePublication(s,data,hash,now),b=await preparePublication(s,data,hash,now);assert.deepEqual(s.items,before);assert.equal(s.xp,0);assert.equal(s.publishJobs.length,1);assert.equal(b.duplicate,true);assert.equal(a.job.id,b.job.id);assert.equal(a.job.body,'확인한 여행 정보입니다.\n\n여행 준비 방법입니다.');assert.equal(a.job.status,'발행 대기');});
test('같은 날짜라도 엠바고 시각·협찬 고지·사진 권한이 부족하면 실행할 수 없다',async()=>{const s=fixture();Object.assign(s.items[0],{type:'sponsor',provided:'식사',embargo:'2026-10-06T10:00'});const {job}=await preparePublication(s,input({images:[{fileId:'photo',afterParagraph:0,rights:'licensed'}]}),hash,now);assert.equal(job.status,'준비 중');for(const term of ['엠바고','권한','고지'])assert.ok(job.checks.issues.some(x=>x.includes(term)));await assert.rejects(()=>claimPublication(s,{jobId:job.id},hash,now),/엠바고/);assert.equal(s.items[0].status,'초안 작성');});
test('준비 후 사진·원고가 바뀌면 다시 검수하고 만료한 접근 확인을 재사용하지 않는다',async()=>{const s=fixture(),{job}=await preparePublication(s,input(),hash,now);s.items[0].draft+='\n\n추가 메모';assert.equal((await publicationChecks(s,job,hash,now)).ready,false);await assert.rejects(()=>claimPublication(s,{jobId:job.id},hash,now),/바뀌/);s.items[0].draft=s.items[0].draft.replace('\n\n추가 메모','');s.publishingAccess.checkedAt='2026-10-04T00:00:00Z';await assert.rejects(()=>claimPublication(s,{jobId:job.id},hash,now),/로그인/);assert.equal((await publicationOverview(s,hash,now)).editorReady,false);});
test('아시아 이슈와 쇼핑은 01시·각1개로 구분하고 게시 완료된 같은 날 슬롯도 재사용하지 않는다',async()=>{const s=fixture();Object.assign(s.items[0],{type:'issue',automatic:true,automaticLane:'asia-issue'});const a=await preparePublication(s,input({lane:'asia-issue',scheduledAt:'2026-10-07T01:00'}),hash,now);assert.equal(a.job.status,'발행 대기');s.items.push({...s.items[0],id:'another'});a.job.status='게시 확인됨';const b=await preparePublication(s,input({itemId:'another',lane:'asia-issue',scheduledAt:'2026-10-07T01:00'}),hash,now);assert.ok(b.job.checks.issues.some(x=>x.includes('이미 준비')));const c=await preparePublication(s,input({itemId:'another',lane:'brand-shopping',scheduledAt:'2026-10-07T02:00',images:[]}),hash,now);for(const term of ['유형','새벽','사진','제휴 링크'])assert.ok(c.job.checks.issues.some(x=>x.includes(term)));});
test('별도 준비 목록에서도 직접 글은 같은 날 4개를 넘을 수 없다',async()=>{const s=fixture();for(let n=0;n<4;n++){const i={...s.items[0],id:'existing'+n};s.items.push(i);await preparePublication(s,input({itemId:i.id}),hash,now);}const {job}=await preparePublication(s,input(),hash,now);assert.ok(job.checks.issues.some(x=>x.includes('최대 4개')));});
test('실행권은 한 번만 확보하고 응답 만료·실패 후 자동 재시도를 막는다',async()=>{const s=fixture(),{job}=await preparePublication(s,input(),hash,now),lease=await claimPublication(s,{jobId:job.id},hash,now);await assert.rejects(()=>claimPublication(s,{jobId:job.id},hash,now),/다시 실행하지/);const list=await publicationOverview(s,hash,'2026-10-06T00:11:00Z');assert.equal(list.jobs[0].status,'확인 필요');assert.throws(()=>cancelPublication(s,job.id),/네이버 결과/);await recordPublication(s,proof(job,lease,{outcome:'failed',message:'응답 연결 끊김'}),hash,now);assert.equal(job.status,'확인 필요');assert.equal(s.items[0].status,'초안 작성');await assert.rejects(()=>preparePublication(s,input(),hash,now),/중복 실행/);});
test('실제 게시 증거·자기 블로그 링크를 검증하고 같은 결과는 중복 적용하지 않는다',async()=>{const s=fixture(),{job}=await preparePublication(s,input(),hash,now),lease=await claimPublication(s,{jobId:job.id},hash,now);for(const bad of [{bodyVerified:false},{imagesVerified:false},{verifiedTitle:'다른 제목'},{postUrl:'https://blog.naver.com/other/123456789'},{postUrl:'https://blog.naver.com:444/withsuzz/123456789'},{postUrl:'https://user:secret@blog.naver.com/withsuzz/123456789'}])await assert.rejects(()=>recordPublication(s,proof(job,lease,bad),hash,'2026-10-06T00:02:00Z'));const a=await recordPublication(s,proof(job,lease),hash,'2026-10-06T00:02:00Z'),b=await recordPublication(s,proof(job,lease),hash,'2026-10-06T00:02:00Z');assert.equal(a.job.status,'게시 확인됨');assert.equal(b.duplicate,true);assert.equal(s.items[0].url,'https://blog.naver.com/withsuzz/123456789');assert.equal(s.items[0].publishedAt,'2026-10-06T00:01:00.000Z');});
test('예약은 네이버 예약 식별값과 시각 확인 후에만 기록하고 실제 게시와 구분한다',async()=>{const s=fixture(),{job}=await preparePublication(s,input({scheduledAt:'2026-10-07T09:00'}),hash,now);await assert.rejects(()=>claimPublication(s,{jobId:job.id},hash,now),/아직/);const lease=await claimPublication(s,{jobId:job.id,mode:'reserve'},hash,now);const data=proof(job,lease,{outcome:'reserved',scheduledAt:'2026-10-07T09:00',reservationUrl:'https://admin.blog.naver.com/withsuzz',reservationId:'naver-reservation-1'});await assert.rejects(()=>recordPublication(s,{...data,reservationId:''},hash,now),/식별값/);await recordPublication(s,data,hash,now);assert.equal(job.status,'예약 확인됨');assert.equal(s.items[0].status,'예약됨');assert.equal(s.items[0].publishedAt,undefined);await recordPublication(s,proof(job,lease,{publishedAt:'2026-10-07T09:01:00+09:00'}),hash,'2026-10-07T00:02:00Z');assert.equal(job.status,'게시 확인됨');});
test('통계 접근이나 대시보드 버튼만으로 글쓰기 접근을 연결됨으로 기록하지 않는다',()=>{const s=fixture();recordPublishingAccess(s,{runUrl,blogId:'withsuzz',editorAccessible:true,loginRequired:false,accountMismatch:false,imageUploadVerified:true,imageVerification:'실제 이미지 삽입 확인 (테스트 fixture)',observedControls:[]},now);assert.equal(s.publishingAccess.editorAccessible,false);recordPublishingAccess(s,{runUrl,blogId:'withsuzz',editorAccessible:true,loginRequired:true,accountMismatch:false,observedControls:['title','body','image','publish']},now);assert.equal(s.publishingAccess.editorAccessible,false);});
test('지난 날짜의 발행을 오늘 실행해 하루 작업량·자동 슬롯을 우회할 수 없다',async()=>{const s=fixture(),{job}=await preparePublication(s,input(),hash,now);s.publishingAccess.checkedAt='2026-10-07T00:00:00Z';await assert.rejects(()=>claimPublication(s,{jobId:job.id},hash,'2026-10-07T00:00:00Z'),/예정 발행일/);assert.equal(job.attempts.length,0);});
