import {chromium} from '/opt/codex/runtimes/cua/lib/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
try{const p=await browser.newPage({viewport:{width:1440,height:1060}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4174');await p.locator('#password').fill('local-test-only');await p.locator('#submit').click();await p.waitForSelector('.hero');await p.getByRole('button',{name:'글쓰기 작업실',exact:true}).click();await p.locator('#writer-title').fill('AI QA 주제');await p.locator('#writer-notes').fill('내 구성과 표현 유지');await p.locator('#draft').fill('내가 쓰던 원고');await p.locator('#writer-type').selectOption('sponsor');assert.equal(await p.locator('#writer-notes').inputValue(),'내 구성과 표현 유지');assert.equal(await p.locator('#draft').inputValue(),'내가 쓰던 원고');await p.locator('#writer-type').selectOption('issue');await p.getByRole('button',{name:'최신 정보·초안 만들기',exact:true}).click();await p.waitForSelector('.ai-preview');assert.equal(await p.locator('#draft').inputValue(),'내가 쓰던 원고');assert.match(await p.locator('#ai-results').textContent(),/최신 정보 확인은 완료되지 않았어요/);
 await p.locator('#draft').fill('아직 저장하지 않은 수정');await p.getByRole('button',{name:'이 결과를 원고에 적용',exact:true}).click();assert.match(await p.locator('#toast').textContent(),/저장하지 않은/);assert.equal(await p.locator('#draft').inputValue(),'아직 저장하지 않은 수정');await p.locator('#draft').fill('내가 쓰던 원고');await p.getByRole('button',{name:'이 결과를 원고에 적용',exact:true}).click();await p.waitForFunction(()=>document.getElementById('draft')?.value?.includes('검증용 제공자'));await p.getByRole('button',{name:'적용 전 원고로 되돌리기',exact:true}).click();await p.waitForFunction(()=>document.getElementById('draft')?.value==='내가 쓰던 원고');
 await p.locator('#revision-scope').selectOption('titles');await p.locator('#revision-note').fill('제목 3개');await p.getByRole('button',{name:'수정안 만들기',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.ai-preview')?.value?.includes('제목 후보'));assert.equal(await p.locator('#draft').inputValue(),'내가 쓰던 원고');assert.equal(await p.getByRole('button',{name:'이 결과를 원고에 적용',exact:true}).count(),0);
 await p.locator('#revision-scope').selectOption('selection');await p.locator('#revision-note').fill('선택한 단어만');await p.locator('#draft').evaluate(t=>{t.focus();t.setSelectionRange(3,4)});await p.getByRole('button',{name:'수정안 만들기',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.ai-preview')?.value==='선택한 부분 수정');await p.getByRole('button',{name:'선택한 부분에 적용',exact:true}).click();await p.waitForFunction(()=>document.getElementById('draft')?.value?.includes('선택한 부분 수정'));assert.equal(await p.locator('#draft').inputValue(),'내가 선택한 부분 수정던 원고');
 await p.screenshot({path:'.sites-runtime/ai-writer-desktop.png',fullPage:true});await p.setViewportSize({width:820,height:1180});await p.screenshot({path:'.sites-runtime/ai-writer-ipad.png',fullPage:true});await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 const itemId=await p.locator('[name="id"]').inputValue(),dates=await p.evaluate(async id=>{const data=await(await fetch('/api/state')).json(),today=data.day,d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+1);await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'saveItem',item:{id,date:today,title:'AI QA 주제'}})});return {today,tomorrow:d.toISOString().slice(0,10)};},itemId);await p.reload();await p.waitForSelector('#draft');await p.setViewportSize({width:1440,height:1060});await p.getByRole('button',{name:'발행 일정',exact:true}).click();const menu=p.locator('.cal-menu[data-id="'+itemId+'"]');await menu.click();await p.waitForSelector('#modal-form');assert.equal(await p.locator('#modal-form [name="id"]').inputValue(),itemId);await p.locator('#f-date').fill(dates.tomorrow);await p.locator('#f-notes').fill('일정에서 수정한 메모');await p.locator('#modal-form button[type="submit"]').click();await p.waitForSelector('#modal-form',{state:'detached'});const saved=await p.evaluate(async id=>(await(await fetch('/api/state')).json()).state.items.find(i=>i.id===id),itemId);assert.equal(saved.date,dates.tomorrow);assert.equal(saved.notes,'일정에서 수정한 메모');assert.equal(saved.draft,'내가 선택한 부분 수정던 원고');await p.screenshot({path:'.sites-runtime/calendar-menu-desktop.png',fullPage:true});assert.deepEqual(errors,[]);console.log('Browser QA passed with test provider: AI preview/apply/undo, scoped revisions, iPad/mobile and calendar menu editing');
}finally{await browser.close();}
