import {readFile,mkdir,writeFile,rm,cp} from 'node:fs/promises';
import {build} from 'esbuild';
let domain=await readFile('worker/domain.mjs','utf8'),worker=await readFile('worker/index.mjs','utf8'),policy=await readFile('worker/editor-policy.mjs','utf8'),ai=await readFile('worker/ai.mjs','utf8');
worker=worker.replace(/^import .* from '\.\/(?:domain|ai|naver|recommendations|reviews|assistant|learning-assistant|publishing|refresh|metrics|naver-posts|formatting|automatic|trends|prompts|quests|products|studio|suzz-prompt)\.mjs';\r?\n/gm,'');ai=ai.replace(/^import .* from '\.\/(?:editor-policy|studio|formatting)\.mjs';\r?\n/gm,'');
worker=worker.replace("'__APP_HTML__'",JSON.stringify(await readFile('public/index.html','utf8'))).replace("'__LOGIN_HTML__'",JSON.stringify(await readFile('public/login.html','utf8')));
const assets={};for(const [name,type] of [['app.css','text/css'],['app.js','text/javascript']])assets['/'+name]={text:await readFile('public/'+name,'utf8'),type:type+'; charset=utf-8'};
worker=worker.replace('ASSETS={}', 'ASSETS='+JSON.stringify(assets));
await rm('dist',{recursive:true,force:true});await mkdir('dist/server',{recursive:true});await mkdir('dist/.openai',{recursive:true});await writeFile('dist/server/app.mjs',(await readFile('worker/naver.mjs','utf8'))+'\n'+(await readFile('worker/recommendations.mjs','utf8'))+'\n'+(await readFile('worker/trends.mjs','utf8'))+'\n'+(await readFile('worker/metrics.mjs','utf8'))+'\n'+(await readFile('worker/naver-posts.mjs','utf8')).replace(/^import .* from '\.\/metrics\.mjs';\r?\n/gm,'')+'\n'+(await readFile('worker/refresh.mjs','utf8')).replace(/^import .* from '\.\/metrics\.mjs';\r?\n/gm,'')+'\n'+(await readFile('worker/reviews.mjs','utf8')).replace(/^import .* from '\.\/(?:metrics|refresh)\.mjs';\r?\n/gm,'')+'\n'+(await readFile('worker/formatting.mjs','utf8')).replace(/^import .* from '\.\/metrics\.mjs';\r?\n/gm,'')+'\n'+(await readFile('worker/publishing.mjs','utf8')).replace(/^import .* from '\.\/formatting\.mjs';\r?\n/gm,'')+'\n'+(await readFile('worker/automatic.mjs','utf8')).replace(/^import .* from '\.\/publishing\.mjs';\r?\n/gm,'')+'\n'+domain.replace(/^import .* from '\.\/metrics\.mjs';\r?\n/gm,'')+'\n'+policy+'\n'+ai+'\n'+(await readFile('worker/prompts.mjs','utf8'))+'\n'+(await readFile('worker/products.mjs','utf8'))+'\n'+(await readFile('worker/studio.mjs','utf8'))+'\n'+(await readFile('worker/suzz-prompt.mjs','utf8'))+'\n'+(await readFile('worker/quests.mjs','utf8')).replace(/^import .* from '\.\/domain\.mjs';\r?\n/gm,'')+'\n'+(await readFile('worker/learning-assistant.mjs','utf8'))+'\n'+(await readFile('worker/assistant.mjs','utf8')).replace(/^import .* from '\.\/(?:ai|learning-assistant|formatting|prompts)\.mjs';\r?\n/gm,'')+'\n'+worker);// npm 의존성(Claude SDK)을 하나의 Worker 파일로 묶는다. 배포 결과는 여전히 dist/server/index.js 한 파일이다.
// Cloudflare는 Worker 파일의 default 외 내보내기를 허용하지 않아요. default만 남겨 묶어요.
await build({stdin:{contents:"export {default} from './app.mjs';",resolveDir:'dist/server',loader:'js'},outfile:'dist/server/index.js',bundle:true,format:'esm',platform:'browser',conditions:['workerd','worker','browser'],target:'es2022',legalComments:'none',charset:'utf8',logLevel:'warning'});if(!process.env.KEEP_APP_MODULE)await rm('dist/server/app.mjs');await cp('.openai/hosting.json','dist/.openai/hosting.json');await cp('drizzle','dist/drizzle',{recursive:true});console.log('Built deployable Worker with embedded UI');
